driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - requirements.txt
    - tests
  state_top:
    base:
      "*":
        - webserver
  pillars_from_directories:
    - source: pillars/
      dest: srv/pillar/
  pillars:
    top.sls:
      base:
        '*':
          - webserver

platforms:
  - name: centos
    driver:
      image: centos/systemd
      privileged: true
      userns_host: true
      
suites:
  - name: webserver
    provisioner:
      salt_bootstrap_options: -qX -p git -p curl -p sudo git 3004.2

verifier:
  name: shell
  remote_exec: false
  command: python3 -m pytest -v tests/
